dist: xenial
language: node_js

notifications:
  email:
    on_success: change
    on_failure: change

git:
  depth: 5

# Always run the latest Node.js version
node_js:
  - "node"

env:
  - MANAGER=npm FLAGS="--global" RUN=web-ext RUNFLAGS="lint"
  - MANAGER=npm FLAGS="--global" RUN=eslint RUNFLAGS="."
  - MANAGER=pip FLAGS="--user" RUN="html5validator" RUNFLAGS="--show-warnings --root ."
  - MANAGER=pip FLAGS="--user" RUN="html5validator" RUNFLAGS="--show-warnings --skip-non-css --root ."
  - MANAGER=pip FLAGS="--user" RUN="html5validator" RUNFLAGS="--show-warnings --skip-non-svg --root ." ALLOWFAILURE="true"

before_script:
  - set -e
  - ${MANAGER} install ${RUN} ${FLAGS}
  - ${RUN} --version
  - ${RUN} --help

script:
  - if [[ -z "${ALLOWFAILURE}" ]]; then ${RUN} ${RUNFLAGS} ; fi;
  - if [[ -n "${ALLOWFAILURE}" ]]; then ${RUN} ${RUNFLAGS} || true ; fi;


jobs:
  include:
    - stage: Deploy
      before_script:
        - set -e
        - if [[ -z "$TRAVIS_TAG" ]] && [[ "$(git diff --name-only ${TRAVIS_COMMIT}^ -- manifest.json)" == "" ]]; then exit 0; fi;
        - npm install -g web-ext
        - if [[ -z "$TRAVIS_TAG" ]]; then sed --in-place 's/verticaltabsreloaded/vtrbeta/' manifest.json; fi;
        - if [[ -z "$TRAVIS_TAG" ]]; then sed --in-place 's/Vertical Tabs Reloaded/VTR (DEVELOPER VERSION)/' manifest.json; fi;
      script:
        - web-ext --version
        - web-ext sign --api-key=${AMO_API_USER} --api-secret=${AMO_API_SECRET} || true
