sudo: false
dist: trusty
language: node_js
# Always run the latest Node.js version

notifications:
  email:
    on_success: never

node_js:
  - "node"

matrix:
  include:
    - env: RUN=addons-linter
    - env: RUN=eslint

before_script:
  - npm install -g $RUN
  - $RUN --version
  - $RUN --help

script:
  - $RUN .
