sudo: false
dist: trusty
language: node_js
# Always run the latest Node.js version

notifications:
  email:
    on_success: change
    on_failure: change

git:
  depth: 5

node_js:
  - "node"

env:
  - RUN=addons-linter
  - RUN=eslint

before_script:
  - npm install ${RUN} --global
  - ${RUN} --version
  - ${RUN} --help

script:
  - ${RUN} .

jobs:
  include:
    - stage: Deploy Developement Versions
      before_script:
        - if ! [[ "$(git diff --name-only ${TRAVIS_COMMIT}^ -- manifest.json)" == "" ]]; then NEWVERSION=true; else NEWVERSION=false; fi;
        - npm install -g web-ext
        - sed --in-place 's/verticaltabsreloaded/vtrbeta/' manifest.json
        - sed --in-place 's/Vertical Tabs Reloaded/VTR (DEVELOPER VERSION)/' manifest.json
      script:
        - web-ext --version
        - if [[ "${NEWVERSION}" == "true" ]]; then web-ext sign --api-key=${AMO_API_USER} --api-secret=${AMO_API_SECRET}; fi;
